### ISSUE TITLE
Problem when installing packages from text file

### ISSUE THREAD

**Issue by wvsonp** [simongrest/farm-pin-crop-detection-challenge#1]
I have problem when installing packages from text file. I tried both pip and conda but the problem exists. Can you tell me which OS are you using. my os is CentOS

**Comment by simongrest** [comment]
I was using Ubuntu 18.04 LTS. What error are you getting? Which package is giving you problems?

**Comment by wvsonp** [comment]
PackagesNotFoundError: The following packages are not available from current channels:

  - google-auth-oauthlib==0.3.0=pypi_0
  - opencv-python==4.1.0.25=pypi_0
  - click-plugins==1.1.1=pypi_0
  - sqlparse==0.3.0=pypi_0
  - pytest-forked==1.0.2=pypi_0
  - thunder-python==1.4.2=pypi_0
  - cachetools==3.1.0=pypi_0
  - rasterio==1.0.28=pypi_0
  - virtualenv==16.5.0=pypi_0
  - mock==2.0.0=pypi_0
  - fastprogress==0.1.21=py_0
  - poyo==0.4.2=pypi_0
  - scikit-learn==0.21.3=pypi_0
  - opencv-contrib-python-headless==4.1.1.26=pypi_0
  - pyasn1-modules==0.2.5=pypi_0
  - requests-oauthlib==1.2.0=pypi_0
  - configparser==3.7.4=pypi_0
  - google-cloud-translate==1.4.0=pypi_0
  - catboost==0.17.1=pypi_0
  - pydot==1.4.1=pypi_0
  - docker-pycreds==0.4.0=pypi_0
  - gitdb2==2.0.5=pypi_0
  - markdown==3.1=pypi_0
  - pyasn1==0.4.5=pypi_0
  - arrow==0.13.1=pypi_0
  - uritemplate==3.0.0=pypi_0
  - six==1.10.0=pypi_0
  - jupyter-http-over-ws==0.0.6=pypi_0
  - google-cloud-bigquery==1.11.2=pypi_0
  - jupyter-aihub-deploy-extension==0.1=pypi_0
  - enum34==1.1.6=pypi_0
  - google-cloud-core==0.29.1=pypi_0
  - eo-learn-geometry==0.6.0=pypi_0
  - googleapis-common-protos==1.5.10=pypi_0
  - google-cloud-language==1.2.0=pypi_0
  - jupyter-latex-envs==1.4.6=pypi_0
  - eo-learn-mask==0.6.0=pypi_0
  - smmap2==2.0.5=pypi_0
  - gcsfs==0.2.1=pypi_0
  - cookiecutter==1.6.0=pypi_0
  - textwrap3==0.9.2=pypi_0
  - docopt==0.6.2=pypi_0
  - zipp==0.5.2=pypi_0
  - nbdime==1.0.5=pypi_0
  - websocket-client==0.56.0=pypi_0
  - python-graphviz==0.13=pypi_0
  - lightgbm==2.2.3=pypi_0
  - google-auth==1.6.3=pypi_0
  - google-cloud-storage==1.15.0=pypi_0
  - pbr==5.2.0=pypi_0
  - descartes==1.1.0=pypi_0
  - pytest-xdist==1.29.0=pypi_0
  - eo-learn-features==0.6.0=pypi_0
  - rsa==4.0=pypi_0
  - category-encoders==2.0.0=pypi_0
  - tifffile==2019.7.26=pypi_0
  - eo-learn-visualization==0.6.0=pypi_0
  - fairing==0.5.2=pypi_0
  - ansiwrap==0.8.4=pypi_0
  - google-api-python-client==1.7.8=pypi_0
  - ipython-sql==0.3.9=pypi_0
  - pytest==5.0.1=pypi_0
  - joblib==0.13.2=pypi_0
  - kaggle==1.5.3=pypi_0
  - importlib-metadata==0.18=pypi_0
  - imbalanced-learn==0.5.0=pypi_0
  - pytorch==1.1.0=py3.7_cuda10.0.130_cudnn7.5.1_0
  - oauth2client==4.1.3=pypi_0
  - google-resumable-media==0.3.2=pypi_0
  - sentinelhub==2.6.0=pypi_0
  - papermill==1.0.0=pypi_0
  - bcolz==1.2.1=pypi_0
  - pyarrow==0.13.0=pypi_0
  - librosa==0.6.3=pypi_0
  - geopandas==0.5.1=pypi_0
  - apipkg==1.5=pypi_0
  - jinja2-time==0.2.0=pypi_0
  - utm==0.5.0=pypi_0
  - jupyter-contrib-core==0.3.3=pypi_0
  - distro==1.4.0=pypi_0
  - pyproj==2.3.1=pypi_0
  - audioread==2.1.6=pypi_0
  - pydicom==1.2.2=pypi_0
  - bayesian-optimization==1.0.1=pypi_0
  - jmespath==0.9.4=pypi_0
  - binaryornot==0.4.4=pypi_0
  - tenacity==5.0.4=pypi_0
  - fastai==1.0.56.dev0=dev_0
  - docker==3.7.2=pypi_0
  - thunder-registration==1.0.1=pypi_0
  - resampy==0.2.1=pypi_0
  - bolt-python==0.7.1=pypi_0
  - prettytable==0.7.2=pypi_0
  - xgboost==0.90=pypi_0
  - scikit-optimize==0.5.2=pypi_0
  - execnet==1.6.0=pypi_0
  - google-api-core==1.10.0=pypi_0
  - google-cloud-dataproc==0.3.1=pypi_0
  - boto3==1.9.228=pypi_0
  - jupyterlab-git==0.5.0=pypi_0
  - jupyter-contrib-nbextensions==0.5.1=pypi_0
  - httplib2==0.12.3=pypi_0
  - fiona==1.8.6=pypi_0
  - update==0.0.1=pypi_0
  - kubernetes==9.0.0=pypi_0
  - pillow-simd==5.3.0.post1=pypi_0
  - s3transfer==0.2.1=pypi_0
  - jupyter-nbextensions-configurator==0.4.1=pypi_0
  - eo-learn-io==0.6.0=pypi_0
  - affine==2.3.0=pypi_0
  - style==1.1.0=pypi_0
  - eo-learn-coregistration==0.6.0=pypi_0
  - oauthlib==3.0.1=pypi_0
  - protobuf==3.7.1=pypi_0
  - botocore==1.12.228=pypi_0
  - grpc-google-iam-v1==0.11.4=pypi_0
  - google-auth-httplib2==0.0.3=pypi_0
  - jupyter-highlight-selected-word==0.2.0=pypi_0
  - pandas-profiling==1.4.1=pypi_0
  - google-cloud-logging==1.10.0=pypi_0
  - datalab==1.1.4=pypi_0
  - msgpack==0.5.6=pypi_0
  - s2cloudless==1.3.0=pypi_0
  - python-slugify==3.0.2=pypi_0
  - imblearn==0.0=pypi_0
  - text-unidecode==1.2=pypi_0
  - shapely==1.6.4.post2=pypi_0
  - pluggy==0.12.0=pypi_0
  - google-cloud==0.34.0=pypi_0
  - grpcio==1.20.1=pypi_0
  - google-cloud-spanner==1.8.0=pypi_0
  - whichcraft==0.5.2=pypi_0
  - snuggs==1.4.6=pypi_0
  - nvidia-ml-py3==7.352.0=pypi_0
  - eo-learn==0.6.0=pypi_0
  - yarg==0.1.9=pypi_0
  - future==0.17.1=pypi_0
  - responses==0.10.6=pypi_0
  - munch==2.3.2=pypi_0
  - eo-learn-core==0.6.0=pypi_0
  - cligj==0.5.0=pypi_0
  - google-cloud-datastore==1.7.3=pypi_0
  - retrying==1.3.3=pypi_0
  - coverage==4.5.3=pypi_0
  - plotly==3.8.1=pypi_0
  - tornado==5.1.1=pypi_0
  - gitpython==2.1.11=pypi_0
  - eo-learn-ml-tools==0.6.0=pypi_0
  - torchvision==0.3.0=py37_cu10.0.130_1
  - pipreqs==0.4.9=pypi_0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org
