### ISSUE TITLE
problem importing S2L1CWCSInput from eolearn

### ISSUE THREAD

**Issue by m0rp43us** [simongrest/farm-pin-crop-detection-challenge#10]
i got this message in the first notebook trying to import necessary packages : 

<ipython-input-3-41b67e50f362> in <module>
     22 from eolearn.core import EOTask, EOPatch, LinearWorkflow, FeatureType, OverwritePermission, \
     23     LoadFromDisk, SaveToDisk, EOExecutor
---> 24 from eolearn.io import S2L1CWCSInput, ExportToTiff
     25 from eolearn.io.local_io import *
     26 from eolearn.mask import AddCloudMaskTask, get_s2_pixel_cloud_detector, AddValidDataMaskTask

ImportError: cannot import name 'S2L1CWCSInput' from 'eolearn.io'

**Comment by sathwik857** [comment]
I'm also getting the same issue @simongrest how did u rectify that error

**Comment by sathwik857** [comment]
And @m0rp43us  have u solved that 
if solved pls tell what to do?
It's urgent pls reply fast

**Comment by m0rp43us** [comment]
S2L1CWCSInput is deprecated,SentinelHubInputTask will work instead.
